### PR TITLE
update drupal core via drupal-project

### PR DESCRIPTION
**Pull request by elizoller**
**GitHub Issue**: (https://github.com/Islandora/documentation/issues/1387)

# What does this Pull Request do?

Points the playbook to the new release of the drupal project which ships with drupal core 8.8.1

# What's new?
* changes release version of drupal-project

# How should this be tested?

* clone playbook
* vagrant up
* make sure drupal 8.8.1 is installed

# Interested parties
@Islandora-Devops/committers

### CODE REVIEW

**Comment by Natkeeran** [comment]
@elizoller 
I am seem to be running into the following issue:
```
TASK [geerlingguy.drupal : Install configured modules with drush.] *************
Monday 06 January 2020  15:10:12 -0500 (0:00:52.137)       0:12:27.398 ******** 
fatal: [default]: FAILED! => {"changed": true, "cmd": ["/var/www/html/drupal/vendor/drush/drush/drush", "pm-enable", "-y", "rdf", "responsive_image", "syslog", "serialization", "basic_auth", "rest", "simpletest", "restui", "devel", "search_api_solr", "search_api_solr_defaults", "facets", "content_browser", "matomo", "pdf", "admin_toolbar", "islandora_defaults", "controlled_access_terms_defaults", "islandora_breadcrumbs", "islandora_iiif", "islandora_oaipmh", "--root=/var/www/html/drupal/web"], "delta": "0:02:28.414459", "end": "2020-01-06 20:12:39.589971", "msg": "non-zero return code", "rc": 1, "start": "2020-01-06 20:10:11.175512", "stderr": "Error: Call to a member function getSettings() on null in /var/www/html/drupal/web/modules/contrib/islandora/modules/islandora_text_extraction/islandora_text_extraction.install on line 16 #0 [internal function]: islandora_text_extraction_install()\n#1 /var/www/html/drupal/web/core/lib/Drupal/Core/Extension/ModuleHandler.php(392): call_user_func_array('islandora_text_...', Array)\n#2 /var/www/html/drupal/web/core/lib/Drupal/Core/Extension/ModuleInstaller.php(323): Drupal\\Core\\Extension\\ModuleHandler->invoke('islandora_text_...', 'install')\n#3 /var/www/html/drupal/web/core/lib/Drupal/Core/ProxyClass/Extension/ModuleInstaller.php(83): Drupal\\Core\\Extension\\ModuleInstaller->install(Array, true)\n#4 /var/www/html/drupal/vendor/drush/drush/src/Drupal/Commands/pm/PmCommands.php(78): Drupal\\Core\\ProxyClass\\Extension\\ModuleInstaller->install(Array, true)\n#5 [internal function]: Drush\\Drupal\\Commands\\pm\\PmCommands->enable(Array, Array)\n#6 /var/www/html/drupal/vendor/consolidation/annotated-command/src/CommandProcessor.php(257): call_user_func_array(Array, Array)\n#7 /var/www/html/drupal/vendor/consolidation/annotated-command/src/CommandProcessor.php(212): Consolidation\\AnnotatedCommand\\CommandProcessor->runCommandCallback(Array, Object(Consolidation\\AnnotatedCommand\\CommandData))\n#8 /var/www/html/drupal/vendor/consolidation/annotated-command/src/CommandProcessor.php(178): Consolidation\\AnnotatedCommand\\CommandProcessor->validateRunAndAlter(Array, Array, Object(Consolidation\\AnnotatedCommand\\CommandData))\n#9 /var/www/html/drupal/vendor/consolidation/annotated-command/src/AnnotatedCommand.php(302): Consolidation\\AnnotatedCommand\\CommandProcessor->process(Object(Symfony\\Component\\Console\\Output\\ConsoleOutput), Array, Array, Object(Consolidation\\AnnotatedCommand\\CommandData))\n#10 /var/www/html/drupal/vendor/symfony/console/Command/Command.php(255): Consolidation\\AnnotatedCommand\\AnnotatedCommand->execute(Object(Drush\\Symfony\\DrushArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#11 /var/www/html/drupal/vendor/symfony/console/Application.php(1000): Symfony\\Component\\Console\\Command\\Command->run(Object(Drush\\Symfony\\DrushArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#12 /var/www/html/drupal/vendor/symfony/console/Application.php(255): Symfony\\Component\\Console\\Application->doRunCommand(Object(Consolidation\\AnnotatedCommand\\AnnotatedCommand), Object(Drush\\Symfony\\DrushArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#13 /var/www/html/drupal/vendor/symfony/console/Application.php(148): Symfony\\Component\\Console\\Application->doRun(Object(Drush\\Symfony\\DrushArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#14 /var/www/html/drupal/vendor/drush/drush/src/Runtime/Runtime.php(118): Symfony\\Component\\Console\\Application->run(Object(Drush\\Symfony\\DrushArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#15 /var/www/html/drupal/vendor/drush/drush/src/Runtime/Runtime.php(49): Drush\\Runtime\\Runtime->doRun(Array, Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#16 /var/www/html/drupal/vendor/drush/drush/drush.php(72): Drush\\Runtime\\Runtime->run(Array)\n#17 /var/www/html/drupal/vendor/drush/drush/drush(4): require('/var/www/html/d...')\n#18 {main}\n [warning] Drush command terminated abnormally.", "stderr_lines": ["Error: Call to a member function getSettings() on null in /var/www/html/drupal/web/modules/contrib/islandora/modules/islandora_text_extraction/islandora_text_extraction.install on line 16 #0 [internal function]: islandora_text_extraction_install()", "#1 /var/www/html/drupal/web/core/lib/Drupal/Core/Extension/ModuleHandler.php(392): call_user_func_array('islandora_text_...', Array)", "#2 /var/www/html/drupal/web/core/lib/Drupal/Core/Extension/ModuleInstaller.php(323): Drupal\\Core\\Extension\\ModuleHandler->invoke('islandora_text_...', 'install')", "#3 /var/www/html/drupal/web/core/lib/Drupal/Core/ProxyClass/Extension/ModuleInstaller.php(83): Drupal\\Core\\Extension\\ModuleInstaller->install(Array, true)", "#4 /var/www/html/drupal/vendor/drush/drush/src/Drupal/Commands/pm/PmCommands.php(78): Drupal\\Core\\ProxyClass\\Extension\\ModuleInstaller->install(Array, true)", "#5 [internal function]: Drush\\Drupal\\Commands\\pm\\PmCommands->enable(Array, Array)", "#6 /var/www/html/drupal/vendor/consolidation/annotated-command/src/CommandProcessor.php(257): call_user_func_array(Array, Array)", "#7 /var/www/html/drupal/vendor/consolidation/annotated-command/src/CommandProcessor.php(212): Consolidation\\AnnotatedCommand\\CommandProcessor->runCommandCallback(Array, Object(Consolidation\\AnnotatedCommand\\CommandData))", "#8 /var/www/html/drupal/vendor/consolidation/annotated-command/src/CommandProcessor.php(178): Consolidation\\AnnotatedCommand\\CommandProcessor->validateRunAndAlter(Array, Array, Object(Consolidation\\AnnotatedCommand\\CommandData))", "#9 /var/www/html/drupal/vendor/consolidation/annotated-command/src/AnnotatedCommand.php(302): Consolidation\\AnnotatedCommand\\CommandProcessor->process(Object(Symfony\\Component\\Console\\Output\\ConsoleOutput), Array, Array, Object(Consolidation\\AnnotatedCommand\\CommandData))", "#10 /var/www/html/drupal/vendor/symfony/console/Command/Command.php(255): Consolidation\\AnnotatedCommand\\AnnotatedCommand->execute(Object(Drush\\Symfony\\DrushArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))", "#11 /var/www/html/drupal/vendor/symfony/console/Application.php(1000): Symfony\\Component\\Console\\Command\\Command->run(Object(Drush\\Symfony\\DrushArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))", "#12 /var/www/html/drupal/vendor/symfony/console/Application.php(255): Symfony\\Component\\Console\\Application->doRunCommand(Object(Consolidation\\AnnotatedCommand\\AnnotatedCommand), Object(Drush\\Symfony\\DrushArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))", "#13 /var/www/html/drupal/vendor/symfony/console/Application.php(148): Symfony\\Component\\Console\\Application->doRun(Object(Drush\\Symfony\\DrushArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))", "#14 /var/www/html/drupal/vendor/drush/drush/src/Runtime/Runtime.php(118): Symfony\\Component\\Console\\Application->run(Object(Drush\\Symfony\\DrushArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))", "#15 /var/www/html/drupal/vendor/drush/drush/src/Runtime/Runtime.php(49): Drush\\Runtime\\Runtime->doRun(Array, Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))", "#16 /var/www/html/drupal/vendor/drush/drush/drush.php(72): Drush\\Runtime\\Runtime->run(Array)", "#17 /var/www/html/drupal/vendor/drush/drush/drush(4): require('/var/www/html/d...')", "#18 {main}", " [warning] Drush command terminated abnormally."], "stdout": "The following module(s) will be enabled: responsive_image, syslog, serialization, basic_auth, rest, simpletest, restui, devel, search_api_solr, search_api_solr_defaults, facets, content_browser, matomo, pdf, admin_toolbar, islandora_defaults, controlled_access_terms_defaults, islandora_breadcrumbs, islandora_iiif, islandora_oaipmh, language, search_api, entity_browser, entity_embed, embed, entity_reference, content_translation, context, controlled_access_terms, name, auto_entitylabel, geolocation, token, field_permissions, eva, field_group, islandora, jsonld, hal, jwt, key, filehash, context_ui, action, media, prepopulate, features_ui, features, config_update, migrate_tools, migrate, migrate_plus, migrate_source_csv, flysystem, islandora_audio, islandora_core_feature, islandora_image, islandora_text_extraction_defaults, islandora_text_extraction, islandora_video, openseadragon, libraries, rest_oai_pmh\n\n // Do you want to continue?: yes.                                              \n\nError: Call to a member function getSettings() on null in islandora_text_extraction_install() (line 16 of /var/www/html/drupal/web/modules/contrib/islandora/modules/islandora_text_extraction/islandora_text_extraction.install).", "stdout_lines": ["The following module(s) will be enabled: responsive_image, syslog, serialization, basic_auth, rest, simpletest, restui, devel, search_api_solr, search_api_solr_defaults, facets, content_browser, matomo, pdf, admin_toolbar, islandora_defaults, controlled_access_terms_defaults, islandora_breadcrumbs, islandora_iiif, islandora_oaipmh, language, search_api, entity_browser, entity_embed, embed, entity_reference, content_translation, context, controlled_access_terms, name, auto_entitylabel, geolocation, token, field_permissions, eva, field_group, islandora, jsonld, hal, jwt, key, filehash, context_ui, action, media, prepopulate, features_ui, features, config_update, migrate_tools, migrate, migrate_plus, migrate_source_csv, flysystem, islandora_audio, islandora_core_feature, islandora_image, islandora_text_extraction_defaults, islandora_text_extraction, islandora_video, openseadragon, libraries, rest_oai_pmh", "", " // Do you want to continue?: yes.                                              ", "", "Error: Call to a member function getSettings() on null in islandora_text_extraction_install() (line 16 of /var/www/html/drupal/web/modules/contrib/islandora/modules/islandora_text_extraction/islandora_text_extraction.install)."]}
```

**Comment by elizoller** [comment]
ok, i'm looking into it. looks like islandora_text_extraction is expecting a field to exist before it does.
```Error: Call to a member function getSettings() on null in islandora_text_extraction_install() (line 16 of /var/www/html/drupal/web/modules/contrib/islandora/modules/islandora_text_extraction/islandora_text_extraction.install).```
`islandora/modules/islandora_text_extraction/islandora_text_extraction.install` contains
```
use Drupal\field\Entity\FieldConfig;

/**
 * Implements hook_install().
 */
function islandora_text_extraction_install() {
  // Add txt extension if it doesn't already exist;.
  $field = FieldConfig::load("media.file.field_media_file");
  $fieldSettings = $field->getSettings();
  $extensions = $fieldSettings['file_extensions'];
  if (!strpos($extensions, 'txt')) {
    $fieldSettings['file_extensions'] .= ' txt';
    $field->set('settings', $fieldSettings);
    $field->save();
  }
}
```
which as far as i can tell media.file.field_media_file should be installed with islandora_defaults which contains the field_media_file in its config/install directory . see : https://github.com/Islandora/islandora_defaults/blob/a6ecb12dac07af38574415fbdff8d02c88067109/config/install/field.field.media.file.field_media_file.yml 
but does the dependency of islandora_text_extraction_defaults from islandora_defaults happen before the config/install from islandora_defaults. if so, i can understand how this would break. maybe @dannylamb can provide some guidance?

**Comment by dannylamb** [comment]
I thought I deleted that file....

**Comment by dannylamb** [comment]
Yeah, I deleted that file in this PR: https://github.com/Islandora/islandora/pull/749/files

So why is the playbook not using the 8.x-1.x branch?

**Comment by elizoller** [comment]
It looks like islandora_defaults pulls dev-8.x-1.x of islandora/islandora in with https://github.com/Islandora/islandora_defaults/blob/8.x-1.x/composer.json but on a clean install (after vagrant destroy and rm roles/external) my islandora module has a most recent commit dated Dec 11 2019 so its several behind. Am I missing a step of clearing cache?

**Comment by dannylamb** [comment]
@elizoller I would say that it's probably a lockfile with composer then, but islandora_defaults doesn't have a lockfile...

**Comment by elizoller** [comment]
I don't see any composer.lock files anywhere
https://packagist.org/packages/islandora/islandora#dev-8.x-1.x still has the commit from Dec 11 2019 though. how does packagist get updated?

**Comment by dannylamb** [comment]
Supposedly automatically.  I'll take a look.

**Comment by dannylamb** [comment]
I just did the packagist equivalent of jiggling the cable, and manually hit the update button for the repository.  On the page it says it was last updated today, along with a statement that this repo is auto-updated.  So hopefully it's back in line :man_shrugging: If it keeps happening I'll report it to packagist.

**Comment by elizoller** [comment]
ok, i'm giving it another shot now.

**Comment by elizoller** [comment]
Passes that step now, but with a new error:
```
TASK [Islandora-Devops.drupal-openseadragon : Install Openseadragon with composer] ***
Thursday 09 January 2020  08:37:55 -0700 (0:00:00.098)       0:18:28.109 ******
fatal: [default]: FAILED! => {"changed": false, "failed": true, "msg": "./composer.json has been updated > DrupalProject\\composer\\ScriptHandler::checkComposerVersion Loading composer repositories with package information Updating dependencies (including require-dev) Nothing to install or update Package container-interop/container-interop is abandoned, you should avoid using it. Use psr/container instead. Package silex/silex is abandoned, you should avoid using it. Use symfony/flex instead. Package zendframework/zend-diactoros is abandoned, you should avoid using it. Use laminas/laminas-diactoros instead. Package zendframework/zend-escaper is abandoned, you should avoid using it. Use laminas/laminas-escaper instead. Package zendframework/zend-feed is abandoned, you should avoid using it. Use laminas/laminas-feed instead. Package zendframework/zend-stdlib is abandoned, you should avoid using it. Use laminas/laminas-stdlib instead. Writing lock file Generating optimized autoload files Installation failed, reverting ./composer.json to its original content. [RuntimeException] Could not delete /var/www/html/drupal/web/sites/default/default.services.yml: require [--dev] [--prefer-source] [--prefer-dist] [--no-progress] [--no-suggest] [--no-update] [--no-scripts] [--update-no-dev] [--update-with-dependencies] [--update-with-all-dependencies] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--] [<packages>]...", "stdout": "./composer.json has been updated\n> DrupalProject\\composer\\ScriptHandler::checkComposerVersion\nLoading composer repositories with package information\nUpdating dependencies (including require-dev)\nNothing to install or update\nPackage container-interop/container-interop is abandoned, you should avoid using it. Use psr/container instead.\nPackage silex/silex is abandoned, you should avoid using it. Use symfony/flex instead.\nPackage zendframework/zend-diactoros is abandoned, you should avoid using it. Use laminas/laminas-diactoros instead.\nPackage zendframework/zend-escaper is abandoned, you should avoid using it. Use laminas/laminas-escaper instead.\nPackage zendframework/zend-feed is abandoned, you should avoid using it. Use laminas/laminas-feed instead.\nPackage zendframework/zend-stdlib is abandoned, you should avoid using it. Use laminas/laminas-stdlib instead.\nWriting lock file\nGenerating optimized autoload files\n\nInstallation failed, reverting ./composer.json to its original content.\n\n                                                                                 \n  [RuntimeException]                                                             \n  Could not delete /var/www/html/drupal/web/sites/default/default.services.yml:  \n                                                                                 \n\nrequire [--dev] [--prefer-source] [--prefer-dist] [--no-progress] [--no-suggest] [--no-update] [--no-scripts] [--update-no-dev] [--update-with-dependencies] [--update-with-all-dependencies] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--] [<packages>]...\n\n", "stdout_lines": ["./composer.json has been updated", "> DrupalProject\\composer\\ScriptHandler::checkComposerVersion", "Loading composer repositories with package information", "Updating dependencies (including require-dev)", "Nothing to install or update", "Package container-interop/container-interop is abandoned, you should avoid using it. Use psr/container instead.", "Package silex/silex is abandoned, you should avoid using it. Use symfony/flex instead.", "Package zendframework/zend-diactoros is abandoned, you should avoid using it. Use laminas/laminas-diactoros instead.", "Package zendframework/zend-escaper is abandoned, you should avoid using it. Use laminas/laminas-escaper instead.", "Package zendframework/zend-feed is abandoned, you should avoid using it. Use laminas/laminas-feed instead.", "Package zendframework/zend-stdlib is abandoned, you should avoid using it. Use laminas/laminas-stdlib instead.", "Writing lock file", "Generating optimized autoload files", "", "Installation failed, reverting ./composer.json to its original content.", "", "                                                                                 ", "  [RuntimeException]                                                             ", "  Could not delete /var/www/html/drupal/web/sites/default/default.services.yml:  ", "                                                                                 ", "", "require [--dev] [--prefer-source] [--prefer-dist] [--no-progress] [--no-suggest] [--no-update] [--no-scripts] [--update-no-dev] [--update-with-dependencies] [--update-with-all-dependencies] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--] [<packages>]...", ""]}
```

**Comment by elizoller** [comment]
I think the key part of that being `[RuntimeException] Could not delete /var/www/html/drupal/web/sites/default/default.services.yml`

**Comment by elizoller** [comment]
@dannylamb  Would it be appropriate to add an ansible task to change the permissions on the `default.services.yml` file to overcome this error?

**Comment by dannylamb** [comment]
Yeah totally.  I'm not sure what best practice is, but it seems like it'd be a good idea to have both settings.php and services.yml belong to the apache user.

Seems weird we're running into this, though.  I'm having a hard time pulling the thread but it looks like it's from composer installing and then it's re-running all of our scripts from drupal-project?

**Comment by elizoller** [comment]
After adding a task to fix that permissions issue (which I think was heavy handed...), I ran into another snag which is described here: https://www.drupal.org/project/features/issues/3091278
Basically features + drush don't play nice so its causing the drush feature imports to fail. I could force this patch in - but again it feels heavy handed. I tried downgrading drush to 9.7.1 instead of 10 but that didn't work either. any other idea for a work around on this?

**Comment by dannylamb** [comment]
@elizoller We can totally [shim a patch into drupal-project](https://groups.drupal.org/node/518975).  That's a thing and lots of folks do it.  Though we've generally tended to just wait these sorts of situations out.

The timing is unfortunate here.  We're about to crank out a version and I'd like to make sure that version ships with a safe Drupal. I think that should be the priority but we should probably discuss how best to proceed with a few more voices.

@Islandora-Devops/committers? Would we be willing to ship with a patched module if we needed to so we have 8.8.1?  I think if we try it we should at least report back on the issue to try and move it along.

**Comment by seth-shaw-unlv** [comment]
I'm fine with including a the patch. It is a simple fix providing a significant boon.

We are running our new instance on 8.8.1 and I've just been living without the drush features import command by relying on the web interface; but if that shim is what we need to get a playbook to run cleanly and Drupal to not constantly complain that I'm not running the most recent version, I'm all for it.

**Comment by whikloj** [comment]
Can we use drupal-console instead of drush?

**Comment by elizoller** [comment]
ooh - good thought.  i'll give it a whirl!

**Comment by dannylamb** [comment]
I'm trying to provision a remote server and I think I'm running smack dab into this as well.  It has nothing to do with 8.8.1 and something to do with us.  I'm pretty sure we should just revert to manually calling the scaffolding and this'll sort itself out.

**Comment by elizoller** [comment]
Testing this now with my latest commit + Danny's PR for disabling auto-scaffold.

**Comment by dannylamb** [comment]
@elizoller I'll test too.  Feels like we're on the verge of this.

**Comment by dannylamb** [comment]
@elizoller There's a feature:import command in `post-install.yml` as well.

**Comment by elizoller** [comment]
Ok i'll change that one too

**Comment by dannylamb** [comment]
@elizoller Did the latest changes work for you.  I'm happy to test to push this along as soon as you feel it's ready.

**Comment by elizoller** [comment]
now i'm hitting a JWT error
"TASK [Islandora-Devops.keymaster : Create Local JWT Key Directory] *************
Monday 27 January 2020  10:48:42 -0700 (0:00:00.410)       0:45:31.885 ********
fatal: [default -> 127.0.0.1]: FAILED! => {"changed": false, "failed": true, "gid": 80, "group": "admin", "mode": "0755", "msg": "/tmp already exists as a link", "owner": "root", "path": "/tmp", "size": 11, "state": "link", "uid": 0}"

**Comment by dannylamb** [comment]
@elizoller Is `/tmp` a link on your local machine?  I just merged changes that force the key generation to happen on one machine (the machine running ansible) and get pushed out to all the otheres.

You can change the directory that the keymaster role tries to write to.  Maybe give this variable a change and see what happens? https://github.com/Islandora-Devops/ansible-role-keymaster/blob/master/defaults/main.yml#L2

**Comment by elizoller** [comment]
I'm building again.

**Comment by dannylamb** [comment]
Ok, from the PR as of now, I made these change and it worked for me:

```diff
diff --git a/inventory/vagrant/group_vars/webserver/drupal.yml b/inventory/vagrant/group_vars/webserver/drupal.yml
index 6e7ea6b..78046e7 100644
--- a/inventory/vagrant/group_vars/webserver/drupal.yml
+++ b/inventory/vagrant/group_vars/webserver/drupal.yml
@@ -18,9 +18,9 @@ drupal_composer_dependencies:
   - "drupal/admin_toolbar:^2.0"
   - "drupal/rest_oai_pmh:^1.0"
   - "islandora/carapace:dev-8.x-3.x"
-  - "islandora/islandora_defaults:dev-8.x-1.x"
+  - "islandora/islandora_defaults:dev-patch-features"
   - "islandora-rdm/islandora_fits:dev-master"
-drupal_composer_project_package: "islandora/drupal-project:8.8.1"
+drupal_composer_project_package: "islandora/drupal-project:dev-no-auto-scaffold"
 drupal_composer_project_options: "--prefer-dist --stability dev --no-interaction"
 drupal_core_path: "{{ drupal_composer_install_dir }}/web"
 drupal_db_user: drupal8
diff --git a/webserver.yml b/webserver.yml
index 7c28392..eb22b04 100644
--- a/webserver.yml
+++ b/webserver.yml
@@ -6,6 +6,9 @@
   vars:
     php_version: "7.2"
 
+  environment:
+    COMPOSER_MEMORY_LIMIT: -1
+
   roles:
     - name: geerlingguy.repo-remi
       when: ansible_os_family == "RedHat"
```

Let me know if that works for you.

**Comment by dannylamb** [comment]
ugh... realizing now this gives you drupal 9 plus patched features, so we're overkill on that one.  maybe you should try it with drush 10 so we're shipping with the latest and we know the patching works.

**Comment by dannylamb** [comment]
I've tested this as is and it's working for me!

**Comment by mjordan** [comment]
I just built a VM using this PR. 8.8.1 installed successfully:

drupal_version

I've added an image repository item and nothing blew up.

**Pull request merged**
