### PR TITLE
Issue 1309

### PR DESCRIPTION
**Pull request by dannylamb**
**GitHub Issue**: Islandora/documentation#1309

For testing https://github.com/Islandora/islandora/pull/761

# What does this Pull Request do?

Pulls in code for https://github.com/Islandora/islandora/pull/761 so it can be tested.

# What's new?
Islandora depending on `drupal/transliterate_filenames`

# How should this be tested?

- Try to upload a file with a comma or a square bracket in it.
- Feel the pain and heartbreak because your file gets rejected
- Pull in this PR
- `vagrant up` 
- Try to upload a file with a comma or a square bracket in it.
- Let your heart fill with joy because your filename got sanitized on the way in, and are now acceptable.

# Interested parties
@Islandora-Devops/committers

### CODE REVIEW

**Comment by seth-shaw-unlv** [comment]
See this comment: https://github.com/Islandora/islandora/pull/761#issuecomment-585902381

**Comment by dannylamb** [comment]
@seth-shaw-unlv Ok, I've added the module to the appropriate variables in the webserver role.  https://github.com/Islandora/islandora/pull/761 now just adds the module to the "suggests" block.  So we "suggest" you use that module, and if you install with our installer... you get it :)

**Comment by seth-shaw-unlv** [comment]
I can probably spin this one up in a few minutes.

**Comment by dannylamb** [comment]
Lets make an issue for that if we don't already have one.

**Pull request merged**
